#pragma once

#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          10
#define MOUSEKEY_MAX_SPEED         2
#define MOUSEKEY_TIME_TO_MAX       20
#define MOUSEKEY_WHEEL_DELAY       0
#define MOUSEKEY_WHEEL_INTERVAL    60
#define MOUSEKEY_WHEEL_MAX_SPEED   3
#define MOUSEKEY_WHEEL_TIME_TO_MAX 30

#define TAPPING_TERM 170
#define TAPPING_FORCE_HOLD